# Generate numpy arrays
questions from https://medium.com/jungletronics/numpy-jupyter-notebook-1182f78ab4e1

1. Creates an array of integers from 10 to 50

In [281]:
import numpy as np
my_list = np.arange(10,51)
my_list

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

2. Create an array of even integers from 10 to 50

In [282]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

3. Creates a 3x3 matrix with values being 1,2,3,...,9

In [283]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

4. Create an array of 20 linearly spaced points between 0 and 1.

In [284]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

5. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [285]:
np.random.sample(25)

array([0.28361775, 0.69642978, 0.21141561, 0.66669554, 0.75055728,
       0.47697645, 0.804077  , 0.37718962, 0.47650315, 0.23418454,
       0.12511709, 0.1779119 , 0.81229516, 0.5315088 , 0.78175754,
       0.4512111 , 0.41093422, 0.80154836, 0.53039174, 0.4173745 ,
       0.78400496, 0.23249281, 0.38139799, 0.47422875, 0.11784929])

6. Create a 10x10 matrix of 100 items spaced evenly at 0.01 steps ranged from 0.01 to 1。

In [286]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Indexing & slicing

Use this 2-Dimensional Array for this exercises

In [287]:
import numpy as np
arr_2_d = np.arange(1,26).reshape(5,5)
print(arr_2_d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


1. Grab the element 20 of the array.

In [288]:
arr_2_d[3][4]

20

2. Grab items 2, 7, 12 of the array.

In [289]:
arr_2_d[0:3,1]

array([ 2,  7, 12])

3. Grab the last row of the array.

In [290]:
arr_2_d[-1]

array([21, 22, 23, 24, 25])

4. Get the sum of all the values in the array.

In [291]:
arr_2_d.sum()

325

5. Get the column sums of the array

In [292]:
np.sum(arr_2_d, axis = 0)

array([55, 60, 65, 70, 75])

6. Get the maximum of each row in the array

In [293]:
np.max(arr_2_d, axis = 1)

array([ 5, 10, 15, 20, 25])

# Conditional selection

In [294]:
# Use this array to test Conditional Selection
arr = np.random.randn(25)
print(arr)

[-0.08694922 -0.78002212 -1.35919527 -1.56769077 -2.32932317 -2.38806215
 -1.02674054  1.4160105   0.03091787  0.83998452 -0.95281668 -0.32792725
  1.16783236  0.58850734 -0.27399407 -1.9561386  -0.50253636  0.15045778
 -0.10841711 -0.48778069  0.79329723 -0.58545225 -1.20599616  1.08679425
 -0.75684813]


Returning the sub array that is in between -0.2 and 0.2.

In [295]:
arr[(arr>-0.2) & (arr<0.2)]

array([-0.08694922,  0.03091787,  0.15045778, -0.10841711])

# Array math

1. Generate two $3\times 3$ random matrices A, B. Compute $A+B$, matrix multiplication $AB$ and $A^{-1}$.  

In [296]:
A = np.random.randint(0,50,(3,3))
B = np.random.randint(0,50,(3,3))

C = A + B

AB = np.matmul(A,B)
Test = A@B

A_inv = np.linalg.inv(A)

print(f'A =\n {A}')
print(f'B =\n {B}')
print(f'A+B =\n {C}')
print(f'AB =\n {AB}')
print(f'A^-1 =\n {A_inv}')
print('Testing out the @ operator found through research, this appears to also do matrix multiplication correctly')
print('It also appears np.dot is not recommended as it does funky stuff with matrices of differing dimension')
print(f'A@B =\n{Test}')

A =
 [[49 47 39]
 [ 5 24  4]
 [16 32 39]]
B =
 [[22 47  7]
 [19  0  4]
 [20 10 47]]
A+B =
 [[71 94 46]
 [24 24  8]
 [36 42 86]]
AB =
 [[2751 2693 2364]
 [ 646  275  319]
 [1740 1142 2073]]
A^-1 =
 [[ 3.27138751e-02 -2.36851694e-02 -3.02846269e-02]
 [-5.30385846e-03  5.21073728e-02 -4.04874691e-05]
 [-9.06919308e-03 -3.30377748e-02  3.80987084e-02]]
Testing out the @ operator found through research, this appears to also do matrix multiplication correctly
It also appears np.dot is not recommended as it does funky stuff with matrices of differing dimension
A@B =
[[2751 2693 2364]
 [ 646  275  319]
 [1740 1142 2073]]


2. Compute eigenvalues and eigenvectors of $A$. 
A refernece for you. https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

In [297]:
E = np.linalg.eig(A)
E

(array([76.5577084+0.j        , 17.7211458+2.92922618j,
        17.7211458-2.92922618j]),
 array([[ 0.87283304+0.j        ,  0.67601151+0.j        ,
          0.67601151-0.j        ],
        [ 0.11905507+0.j        , -0.10942725-0.35906108j,
         -0.10942725+0.35906108j],
        [ 0.4732741 +0.j        , -0.41030218+0.48348876j,
         -0.41030218-0.48348876j]]))

# Functions

1. Define a function with name $h$ that returns that value $h(x)=\frac{e^{x/2}+e^{-x/2}}{2}$.

In [298]:
def h(x):
    return (np.exp(x/2) + np.exp(-x/2))/2

2. Define a function with name $f$ that calls $h(x)$ in question 1 and returns $f(x)=e^{-x/2}(h(x)+h(2x))$. Compute $f(1)$.

In [299]:
def f(x):
    return np.exp(-x/2)*(h(x)+h(2*x))

f(1)

1.61986543601

3. Define a function with inputs being two $3\times 3$ random matrices $A, B$, and returns two matrices $A+B$ and matrix multiplication $AB$.

In [300]:
def matrix_math(A,B):
    if type(A) == np.ndarray and type(B) == np.ndarray:
        if A.shape == (3,3) and B.shape == (3,3):
            return A+B , np.matmul(A,B)
    else:
        return None
    
matrix_math(A,B) 


(array([[71, 94, 46],
        [24, 24,  8],
        [36, 42, 86]]),
 array([[2751, 2693, 2364],
        [ 646,  275,  319],
        [1740, 1142, 2073]]))

# Numerical solutions of ODE

1. Define a function to find the numerical solution of $x'=x \cos(t)$, $x(0)=1$ using Euler's method. Use step size 0.01, and find the solution $x(t)$ with $t\in [0,50]$. Output the solution as a numpy array.

In [301]:
def Euler(f,t,c):
    solution = np.zeros((len(c),len(t)))
    h = (t[-1]-t[0])/len(t)
    solution[:,0] = c
    for i in range(1,len(t)):
        k = f(t[i-1],solution[:,i-1]) 
        solution[:,i] = solution[:,i-1] + (h+np.zeros(len(c)))*k
    
    return solution[0]

In [302]:
def f(t,x):
    return x*np.cos(t)
t = np.arange(0,50.01,0.01)
x_0 = [1]

euler_solution = Euler(f,t,x_0)
print(euler_solution)

[1.         1.009998   1.02009546 ... 0.66657679 0.67297149 0.67944616]


In [303]:
#Compare to actual solution e^(sin(t))
sol = np.exp(np.sin(50))
print(f'True solution: {sol}')
print(f'Error: {abs(sol - euler_solution[-1])}')
 

True solution: 0.7692226237074062
Error: 0.08977646827668129


2. Define a function to find the numerical solution of $x''+x=0$, $x(0)=3$, $x'(0)=0$ using Euler's method. Use step size 0.01, and find the solution $x(t)$ with $t\in [0,50]$.  Output the solution as a numpy array.

In [304]:
# x' = z
# z' = -x  so f(x,z) = (x,z)' = (z,-x)
def g(t,x):
    return [x[1],-x[0]]
x_0 = [3,0]

euler_solution_2 = Euler(g,t,x_0)

print(euler_solution_2)
#Compare to actual solution 3cos(t)
sol = 3*np.cos(50)
print(f'True solution: {sol}')
print(f'Error: {abs(sol - euler_solution_2[-1])}')

[3.         3.         2.99970012 ... 3.68248584 3.69375961 3.70466528]
True solution: 2.89489808547634
Error: 0.8097671944998663


##  Just for fun, let's try to code up a Runge-Kutta solver to redo these problems

In [305]:
def RK(f,t,c):
    solution = np.zeros((len(c),len(t)))
    h = (t[-1]-t[0])/len(t)
    solution[:,0] = c
    for i in range(1,len(t)):
        k1 = f(t[i-1],solution[:,i-1]) 
        k2 = f(t[i-1] + h/2, solution[:,i-1] + (h + np.zeros(len(c)))*(k1)/2)
        k3 = f(t[i-1] + h/2, solution[:,i-1] + (h + np.zeros(len(c)))*(k2)/2)
        k4 = f(t[i-1] + h, solution[:,i-1] + (h + np.zeros(len(c)))*(k3))
        solution[:,i] = solution[:,i-1] + (1/6 + np.zeros(len(c)))*(k1 + (2+np.zeros(len(c)))*k2 + (2+np.zeros(len(c)))*k3 + k4)*(h + np.zeros(len(c)))
    
    return solution[0]

In [306]:
#Problem 1
def f(t,x):
    return x*np.cos(t)
t = np.arange(0,50.01,0.01)
x_0 = [1]

test_solution = RK(f,t,x_0)
print(test_solution)
#Compare to actual solution e^(sin(t))
sol = np.exp(np.sin(50))
print(f'True solution: {sol}')
print(f'Error: {abs(sol - test_solution[-1])}')

[1.         1.01004798 1.0201959  ... 0.75460257 0.76188717 0.76926301]
True solution: 0.7692226237074062
Error: 4.038453735355496e-05


In [307]:
#Problem 2
def g(t,x):
    return [x[1], -x[0]]
x_0 = [3,0]

test_solution_2 = RK(g,t,x_0)

test_solution_2

#Compare to actual solution 3cos(t)
sol = 3*np.cos(50)
print(f'True solution: {sol}')
print(f'Error: {abs(sol - test_solution_2[-1])}')

True solution: 2.89489808547634
Error: 0.008014229883858803
